version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/webapp
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"

  web:
    build:
      context: containers/nginx
    volumes:
      - .:/webapp
    ports:
      - "80:80"
    depends_on:
      - app
