version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/webapp

  web:
    build:
      context: ./containers/nginx
    volumes:
      - .:/webapp
    ports:
      - "80:80"
    depends_on:
      - app
