default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  pool: 5
  username: root
  password: password
  host: db


development:
  <<: *default
  database: development_db
  host: db
  password: password

test:
  <<: *default
  host: 127.0.0.1
  database: sample_test #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい
  password: 

production:
  <<: *default
  port: 3306
  host: database-2.cfwpkyig5zfz.us-east-2.rds.amazonaws.com
  database: test_db
  username: admin
  password: password
  
# production:
#   <<: *default
#   port: 3306
#   host: aa18ommas3el3jk.clrfy79vwafb.ap-northeast-1.rds.amazonaws.com
#   database: ebdb
#   username: kinntai
#   password: password